sudo: required
dist: trusty
language: go
env:
  global:
    - GO111MODULE=on
go:
  - 1.13.7
script:
  - |
    if [ -n "${TRAVIS_TAG}" ]; then
      export RELEASE_VER=${TRAVIS_TAG}
    elif [ "${TRAVIS_BRANCH}" == "master" ]; then
      export DOCKER_IMAGE_TAG=master
    else if [ -n "${TRAVIS_TAG}" ]; then
      # use a release version as a docker image tag
      export RELEASE_VER=${TRAVIS_TAG}
    else
      export RELEASE_VER=`git rev-parse --short HEAD`
    fi
    make all &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.txt -service=travis-pro -repotoken $COVERALLS_TOKEN
